## 00. PyTorch Fundamentals
### Resource Link: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
print(torch.__version__)

2.1.2+cu118


### Introduction to tensors

#### Creating tensors

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#### Random Tensors

In [18]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8471, 0.0068, 0.8164, 0.6481],
        [0.7311, 0.4451, 0.4503, 0.7138],
        [0.4725, 0.8092, 0.9758, 0.4894]])

In [19]:
random_tensor.ndim

2

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # Height, Width, Color Channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#### Zeros and ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [23]:
# Create a tensor of all ones
zeros = torch.ones(size = (3,4))
zeros, zeros.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

#### Creating a range of tensors and tensors-like

In [25]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=10, end=0, step=-1)
zero_to_ten

tensor([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [27]:
# Creating tensors like
ten_zeros = torch.ones_like(zero_to_ten)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed 
                               device=None, # defaults to None or what device is your tensor on
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor

tensor([3., 6., 9.])

In [30]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

#### Manipulating Tensors (tensor operation)

Tensor operations include:
* Addition
* Subtraction 
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [34]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply it by 10
tensor*10

tensor([10, 20, 30])

In [36]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [37]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [38]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

#### PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplication) and torch.add() to perform basic operations.

In [39]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [40]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

#### However, it is more common to use the operator symbols like * instead of torch.mul()

In [42]:
# Element-wise multiplication (each element multiplies its equivalent)

print(tensor, "*", tensor)
print("Equals: ", tensor* tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


#### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise Multiplication
2. Matrix Multiplication (dot product)

In [43]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [44]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor 

tensor(14)

### *One of the most common errors in deep learning (shape errors)*

In [46]:
# Shapes need to be in the right way 
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will give an error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [47]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [49]:
#torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])