## 00. PyTorch Fundamentals
### Resource Link: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
print(torch.__version__)

2.1.2+cu118


### Introduction to tensors

#### Creating tensors

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

#### Random Tensors

In [16]:
# Create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7935, 0.3944, 0.9431, 0.8741],
        [0.4548, 0.9676, 0.7984, 0.9133],
        [0.0062, 0.4472, 0.6700, 0.7107]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # Height, Width, Color Channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

#### Zeros and ones

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [20]:
# Create a tensor of all ones
zeros = torch.ones(size = (3,4))
zeros, zeros.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

#### Creating a range of tensors and tensors-like

In [21]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=10, end=0, step=-1)
zero_to_ten

tensor([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [22]:
# Creating tensors like
ten_zeros = torch.ones_like(zero_to_ten)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [23]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed 
                               device=None, # defaults to None or what device is your tensor on
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor

tensor([3., 6., 9.])

In [24]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [25]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

#### Manipulating Tensors (tensor operation)

Tensor operations include:
* Addition
* Subtraction 
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [26]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [27]:
# Multiply it by 10
tensor*10

tensor([10, 20, 30])

In [28]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [29]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [30]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

#### PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplication) and torch.add() to perform basic operations.

In [31]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [32]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

#### However, it is more common to use the operator symbols like * instead of torch.mul()

In [33]:
# Element-wise multiplication (each element multiplies its equivalent)

print(tensor, "*", tensor)
print("Equals: ", tensor* tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


#### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise Multiplication
2. Matrix Multiplication (dot product)

In [34]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [35]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor 

tensor(14)

### *One of the most common errors in deep learning (shape errors)*

In [36]:
# Shapes need to be in the right way 
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will give an error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [37]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [38]:
#torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Finding the min, max, mean, sum, etc. (Tensor Aggregation)

In [39]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")

# print(f"Mean: {x.mean()}") #This will throw an error
print(f"Mean: {x.type(torch.float32).mean()}") #Won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [41]:
torch.max(x)
torch.min(x)
torch.mean(x.type(torch.float32))
torch.sum(x)

tensor(450)

### Finding the positional min and max

In [42]:
#Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Index where max value occurs: 2
Index where min value occurs: 0


### Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - Reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combining multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Removes all '1' dimensions from a tensor
* Unsqueeze - Add a '1' dimenstion to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [43]:
# let's create a tensor 
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [44]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [45]:
# Change the view 
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [46]:
# Changing z changes z (becuase a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [47]:
# Stack tensors on top of each other 
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"New Tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])


In [63]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"New Tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [65]:
# torch.permute - rearranges the dimensions of a target tensor in a specificied order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # Shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (Selecting data from tensors)
#### Indexing with PyTorch is similar to indexing with NumPy

In [66]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [67]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [68]:
# Let's index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [73]:
# Let's index on the most inner bracket (dim = 2)
x[0][2][2]

tensor(9)

In [74]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [75]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[: , :, 1]

tensor([[2, 5, 8]])

In [76]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [77]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

### PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library and because of this, PyTorch has functionality to interact with it.

* torch.from_numpy(ndarray): NumPy array    --> PyTorch Tensor
* torch.Tensor.numpy()     : PyTorch Tensor --> NumPy array



In [82]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) 
# Warning:  When converting from numpy --> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
# Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [84]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [85]:
# Change the tensor, what happend to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### REPRODUCIBILITY (trying to take random out of random)

In short how a neural network learns:
'Start with random numbers --> tensor operations --> update random numbers to try and make them better representations of the data --> again --> again --> again...'

To reduce the randomness in neural network and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.



In [91]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.2234, 0.7232, 0.8598, 0.1596],
        [0.6139, 0.3677, 0.9439, 0.6787],
        [0.3003, 0.7296, 0.1477, 0.7063]])
tensor([[0.4386, 0.5314, 0.9605, 0.8597],
        [0.6831, 0.0456, 0.8249, 0.0591],
        [0.6458, 0.4772, 0.4204, 0.7158]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [100]:
# Let's make some random but reproducible tensors

# Set the random seed 
RANDOM_SEED = 2

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.6147, 0.3810, 0.6371, 0.4745],
        [0.7136, 0.6190, 0.4425, 0.0958],
        [0.6142, 0.0573, 0.5657, 0.5332]])
tensor([[0.6147, 0.3810, 0.6371, 0.4745],
        [0.7136, 0.6190, 0.4425, 0.0958],
        [0.6142, 0.0573, 0.5657, 0.5332]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [102]:
# Check if PyTorch has access to a GPU 
torch.cuda.is_available()

True

In [103]:
# Set device type 
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [104]:
# Count number of devices
torch.cuda.device_count()

1

In [105]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [ ]:
# # If tensor is on GPU, can't transform it to NumPy (this will error)
# tensor_on_gpu.numpy()

In [106]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)